apiVersion: v1
kind: Service
metadata:
  name: openai-agent-service
  namespace: backend
spec:
  selector:
    app: openai-agent-service
  ports:
    - name: http
      port: 80
      targetPort: 8091
  type: ClusterIP
